# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Title
#'
#' @param x 
#'
#' @return # coming soon
#' @export
#'
#' @examples # coming soon
rowSumsC <- function(x) {
    .Call('bplmnist_rowSumsC', PACKAGE = 'bplmnist', x)
}

#' Title
#'
#' @param x 
#' @param y 
#' @param p 
#'
#' @return # coming soon
#' @export
#'
#' @examples # coming soon
calcDist <- function(x, y, p) {
    .Call('bplmnist_calcDist', PACKAGE = 'bplmnist', x, y, p)
}

